config/routes.rb
RinuiteSweet::Application.routes.draw do
  namespace :admin do
    resources :questions
  end

  match '/age'              => 'age#index'
  match '/age/:id'          => 'age#index'
  match '/age/verify'       => 'age#verify'

  match 'content/:content'  => 'main#index'

  match '/qr'               => 'qr#index'

  match '/share/:id/:text'  => 'share#index'

  scope "/:locale" do
    match '/'                     => 'main#index'
    match '/age'                  => 'age#index'
    match '/age/verify'           => 'age#verify'
    match '/age/verify/:content'  => 'age#verify'
    match '/age/:id'              => 'age#index'
    match '/questions.json'       => 'questions#index'
    match '/main/share/:id'       => 'main#share'
    match '/iphone'               => 'facebook#giveaway'
    match '/party-pack'           => 'facebook#partypack'
    match '/corkscrew'            => 'facebook#corkscrew'
    match '/facebook'             => 'facebook#index'
    match '/share/:id'            => 'share#index'
    match '/:content'   => 'main#index'

  end

  constraints(:host => "riuniteice.com") do
    match '/', :to => redirect {|params, req| "http://www.riuniteice.com/en#{params[:path]}"}
  end
  constraints(:host => "riunitechill.com") do
    match '/', :to => redirect {|params, req| "http://www.riunitechill.com/en#{params[:path]}"}
  end

  constraints(:host => "riunitedulce.com") do
    match '/', :to => redirect {|params, req| "http://www.riunitedulce.com/es#{params[:path]}"}
  end
  constraints(:host => "riunitevino.com") do
    match '/', :to => redirect {|params, req| "http://www.riunitevino.com/es#{params[:path]}"}
  end
  constraints(:host => "www.riunitedulce.com") do
    match '/', :to => redirect {|params, req| "http://www.riunitedulce.com/es#{params[:path]}"}
  end
  constraints(:host => "www.riunitevino.com") do
    match '/', :to => redirect {|params, req| "http://www.riunitevino.com/es#{params[:path]}"}
  end

  root :to => redirect('/en');
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :en, :es
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < AdminController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to [:admin, @question], notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to [:admin, @question], notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to admin_questions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  # GET /:locale/questions.json
  def index
    #language_question_index = 'questions.' + params[:locale].to_s
    @questions = Question.find(:all).map {
      |question| {
        question.id =>
        (params[:locale].to_s == 'en') ? question.en : question.es
      }
    }

    respond_to do |format|
      format.json { render json: @questions }
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/admin/questions/_form.html.erb
<%= form_for([:admin, @question]) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :en %><br />
    <%= f.text_area :en %>
  </div>
  <div class="field">
    <%= f.label :es %><br />
    <%= f.text_area :es %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @question] %> |
<%= link_to 'Back', admin_questions_path %>

app/views/admin/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>En</th>
    <th>Es</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.en %></td>
    <td><%= question.es %></td>
    <td><%= link_to 'Show', [:admin, question] %></td>
    <td><%= link_to 'Edit', edit_admin_question_path(question) %></td>
    <td><%= link_to 'Destroy', [:admin, question], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_admin_question_path %>

app/views/admin/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_questions_path %>

app/views/admin/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>En:</b>
  <%= @question.en %>
</p>

<p>
  <b>Es:</b>
  <%= @question.es %>
</p>


<%= link_to 'Edit', edit_admin_question_path(@question) %> |
<%= link_to 'Back', admin_questions_path %>